var argx = argument0;
var argy = argument1;
var argl = argument2 / 2;
argh2 = argument3 / 2;
argh1 = argument4 / 2;
var aa = argument5;
var c = argument6;
var a = argument7;
var r1 = point_direction(0, 0, argl, argh1);
var r2 = point_direction(0, 0, argl, argh2);
var l1 = length(argl, argh1);
var l2 = length(argl, argh2);
draw_primitive_begin(pr_trianglelist);
draw_vertex_color(argx + lengthdir_x(l1, aa + r1), argy + lengthdir_y(l1, aa + r1), c, a);
draw_vertex_color(argx + lengthdir_x(l2, (aa + 180) - r2), argy + lengthdir_y(l2, (aa + 180) - r2), c, a);
draw_vertex_color(argx + lengthdir_x(l2, aa + 180 + r2), argy + lengthdir_y(l2, aa + 180 + r2), c, a);
draw_vertex_color(argx + lengthdir_x(l2, aa + 180 + r2), argy + lengthdir_y(l2, aa + 180 + r2), c, a);
draw_vertex_color(argx + lengthdir_x(l1, aa - r1), argy + lengthdir_y(l1, aa - r1), c, a);
draw_vertex_color(argx + lengthdir_x(l1, aa + r1), argy + lengthdir_y(l1, aa + r1), c, a);
draw_primitive_end();
