StatInfo[translate_stats(0, "out"), 0] = "Body Damage"
StatInfo[translate_stats(1, "out"), 0] = "Max Health"
StatInfo[translate_stats(2, "out"), 0] = "Bullet Speed"
StatInfo[translate_stats(3, "out"), 0] = "Bullet Health"
StatInfo[translate_stats(4, "out"), 0] = "Bullet Penetration"
StatInfo[translate_stats(5, "out"), 0] = "Bullet Damage"
StatInfo[translate_stats(6, "out"), 0] = "Reload"
StatInfo[translate_stats(7, "out"), 0] = "Movement Speed"
StatInfo[translate_stats(8, "out"), 0] = "Shield Regeneration"
StatInfo[translate_stats(9, "out"), 0] = "Shield Capacity"
StatInfo[translate_stats(0, "out"), 1] = "[1]"
StatInfo[translate_stats(1, "out"), 1] = "[2]"
StatInfo[translate_stats(2, "out"), 1] = "[3]"
StatInfo[translate_stats(3, "out"), 1] = "[4]"
StatInfo[translate_stats(4, "out"), 1] = "[5]"
StatInfo[translate_stats(5, "out"), 1] = "[6]"
StatInfo[translate_stats(6, "out"), 1] = "[7]"
StatInfo[translate_stats(7, "out"), 1] = "[8]"
StatInfo[translate_stats(8, "out"), 1] = "[9]"
StatInfo[translate_stats(9, "out"), 1] = "[0]"
StatInfo[translate_stats(0, "out"), 2] = merge_color($1B15C4, c_black, 0.4)
StatInfo[translate_stats(1, "out"), 2] = merge_color($15A0DB, c_black, 0.4)
StatInfo[translate_stats(2, "out"), 2] = merge_color($D66633, c_black, 0.4)
StatInfo[translate_stats(3, "out"), 2] = merge_color($16A039, c_black, 0.4)
StatInfo[translate_stats(4, "out"), 2] = 1417435
StatInfo[translate_stats(5, "out"), 2] = 1775044
StatInfo[translate_stats(6, "out"), 2] = 1482809
StatInfo[translate_stats(7, "out"), 2] = 14050867
StatInfo[translate_stats(8, "out"), 2] = 6687362
StatInfo[translate_stats(9, "out"), 2] = merge_color($660A82, c_black, 0.4)
