module.exports = {
    "MODE": "tdm",
    "serverName": "Void Walkers",
    "TEAM_AMOUNT": 1,
    "MODE": "tdm",
    "WIDTH": 2000,
    "HEIGHT": 2000,
    "X_GRID": 5,
    "Y_GRID": 5,
    "MAX_FOOD": 0,
    "MAX_NEST_FOOD": 0,
    "MAX_CRASHERS": 0,
    "MAX_SANCS": 0,
    "ROOM_SETUP": [
        ["wall","wall","door","wall","wall"],
        ["wall","norm","norm","norm","wall"],
        ["door","norm","domm" ,"norm","door"],
        ["wall","norm","norm","norm","wall"],
        ["wall","wall","door","wall","wall"],
    ],
    "PLAYER_SPAWN_TILES": ["norm"],
    "DO_BASE_DAMAGE": false,
    "BOTS": 0,
    "BORDER_FORCE": 0,
    "OUTSIDE_ROOM_DAMAGE": 0,
    "BOSS_SPAWN_TIMER": Infinity,
    "LEVEL_ZERO_UPGRADES": true,
}